language: ruby
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0

# Bundler 1.13 added support for `ruby RUBY_VERSION` in the Gemfile
before_install: gem install bundler -v '>= 1.13.0'

sudo: false
notifications:
  email:
    - toolbag@gmail.com
    - christian@minimul.com
